//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirilenSinav
    {
        public int GirilenSinavId { get; set; }
        public int GOgrId { get; set; }
        public int GSinavId { get; set; }
        public string VerilenCevaplar { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Sinavlar Sinavlar { get; set; }
    }
}
