//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinav.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secenekler
    {
        public int SecenekId { get; set; }
        public int SecenekSoruId { get; set; }
        public string SecenekMetni { get; set; }
    
        public virtual Sorular Sorular { get; set; }
    }
}
